PROC  DATASETS  NOLIST;
COPY IN=SASHELP OUT=WORK;
SELECT CARS;
QUIT;
RUN;
PROC  DATASETS  NOLIST;
COPY IN=SASHELP OUT=WORK;
SELECT CLASS;
QUIT;
RUN;


/* WRITING MACRO THAT CALLS MACRO */

%MACRO DOTBOTH(DNAME1=,DNAME2= ,LIST1=,LIST2=);
		%SRTCARS(DSN=&DNAME1,BYLIST=&LIST1)
		%PRNTCLASS(DSN=&DNAME2,VARLIST=&LIST2)
%MEND DOTBOTH;
%DOTBOTH(DNAME1=CARS,DNAME2=,LIST1=ORIGIN,LIST2=)


%MACRO SRTCARS(DSN=,BYLIST=);
PROC PRINT DATA=&DSN;/*CARS*/
BY &BYLIST;/*MAKE */
RUN;
%MEND SRTCARS;


%MACRO PRNTCLASS(DSN=,VARLIST=);
PROC PRINT DATA=&DSN;/*CLASS*/
VAR &VARLIST; /*AGE NAME SEX HEIGHT*/
RUN;
%MEND PRNTCLASS;