/* HERE WE ARE TRYING TO ADD MULTIPLE NUMERIC CONSTANT WHEN THE AGE DIFFERS/INCREMENTS */
/* SO ,THE OBJECTIVE IS TO ADD 1 FOR AGE 16,ADD 2 FOR AGE 15,ADD 3 FOR AGE 14,ADD 4 FOR AGE 13, */
/* ADD 5 FOR AGE 13,ADD 6 FOR AGE 12 etc. */

#NOTE 
/* PLEASE DO NOTE WE HAVE TWO WAY FOR THIS, */
/* ONE USING ARRAY AND DO LOOP */
/* ANOTHER USING MACRO AND SYMGET */
data have; 
set sashelp.class(keep=name age height);
run;

proc sort data=have;by name descending age;run;

proc transpose data=have out=NIRAJ  (DROP=_NAME_) PREFIX=AGE;
id age;
var height;
by name;
run;

PROC STDIZE DATA=NIRAJ REPONLY MISSING=0 out=PASA;RUN;


DATA CCC;
SET PASA;
ARRAY FINAL{*}_NUMERIC_;
ARRAY SEMI{6}_TEMPORARY_(1,2,3,4,5,6);
DO i= 1 to dim(FINAL);
FINAL{i}=FINAL{i}+SEMI{i};
END;
RUN;


************************************************;
DATA A;
SET SASHELP.CLASS;
RUN;

%LET AG11=5;
%LET AG12=6;
%LET AG13=7;
%LET AG14=8;
%LET AG15=9;
%LET AG16=10;

/* THE BELOW IF CONDITION CODE CAN BE RE-WRITTEN VERY PRECISELY USING SYMGET AND MACRO STATEMENT */
DATA NEW;
SET A;
IF AGE=11 THEN NEWHEIGHT=HEIGHT*5;
IF AGE=12 THEN NEWHEIGHT=HEIGHT*6;
IF AGE=13 THEN NEWHEIGHT=HEIGHT*7;
IF AGE=14 THEN NEWHEIGHT=HEIGHT*8;
.
.
.
.
IF AGE=16 THEN NEWHEIGHT=HEIGHT*10
;
/* ALTERNATIVEYLT TO ABOVE CODE,WE CAN DO THIS */


DATA NEWMACROSTYLE;
SET A;
NEWHEIGHT=HEIGHT*SYMGET(CATT('AG',AGE));
RUN;
TO UNDERSTAND THIS PROGRAM,THINK THIS WAY,SAS WORKS ON OBS BY OBS RIGHT??
SO,IMAGINE ON THE VERY FIRST OBS,WHEN SAS EXECUTES,
NEW VARIABLE CALLED NEWHIGHT IS CREATED,ANOTHER VIRTUAL? VARIABLE CALLED AG IS CREATED
AFTER AG IS CREATED,THE VALUE OF AGE SUCH AS 11,12 13 IS CONCATANATED TO EACH OF THEM
SO THE PICTURE/TABLE WOULD BE LIKE THIS.
STEPT-1;
AG AGE NEWHEIGHT
AG	11	 ??
AG	12   ??
AG  13   ??
AG  14   ??
AG  15   ??
AG  16   ??

STEP-1.2(AFTER CONCATENATION)
AG AGE 	  AG			NEWHEIGHT
AG	11	 &AG11			??
AG	12   &AG12			??
AG  13   &AG13			??
AG  14   &AG14			??
AG  15   &AG15			??
AG  16   &AG16			??


STEP-2;
IMAGINE WITH FIRST OBS,
AG VARIABLE IS CONCATINATED WITH AGE VALUE,THAT MAKES IT
AG11,BUT SINCE WE ALREADY DEFINED MACRO CALLED AGE11,SYMGET CALL ROUTINE WILL CALL 
THE MACRO CALLED AGE11(&AGE11),FROM MACRO SYMBOL TABLE AND ASSIGN IT TO PDV,
SO THIS MACRO EXECUTES THE VALUE AS DEFINED FOR 
&AGE11 WILL BE RESOLVED TO SAY,5.
NOW THIS VALUE WILL BE MULTIPLIED TO HEIGHT AS
NEWHEIGHT=HEIGHT*SYMGET(CATT('AG',AGE));









libname kanchan '/folders/myfolders' ;
