PROC FORMAT;
PICTURE namefmt
LOW-HIGH='%B %Y' (DATATYPE=date)
;
RUN;

PROC SQL;
CREATE TABLE subset AS
SELECT date as sheet_date FORMAT=namefmt15., *
FROM sashelp.citiday
WHERE date BETWEEN '01JAN1988'd AND '31AUG1988'd
ORDER BY DATE
;;;;
QUIT;

OPTIONS NOBYLINE;
ODS TAGSETS.EXCELXP FILE="ex6.1.4.xml" OPTIONS (SHEET_NAME="#BYVAL1");
PROC PRINT DATA=subset LABEL NOOBS;
BY sheet_date;
RUN;
ODS TAGSETS.EXCELXP CLOSE;
